import { CropMarketData, MandiRecord, MarketPrice } from '../types';

export const DEMO_CROP_MARKET_DATA: CropMarketData[] = [
  {
    cropId: 'soybean',
    cropName: 'Soybean (Yellow)',
    cropHindi: 'सोयाबीन (पीला)',
    cropOdia: 'ସୋୟାବିନ୍ (ହଳଦିଆ)',
    icon: '🌱',
    category: 'Oilseeds',
    msp: 4892,
    currentDate: '20 Aug 2026',
    avgModalPrice: 4845,
    highestPrice: 5180,
    lowestPrice: 4300,
    bestMandiName: 'Ujjain Sanwer APMC',
    bestMandiPrice: 4920,
    bestMandiNetPayout: 4840,
    overallTrend: 'increasing',
    priceChangePercent: 3.2,
    totalArrivalTonnes: 1420,
    mandis: [
      {
        id: 'mandi_sb_ujjain',
        mandiName: 'Ujjain Sanwer APMC',
        district: 'Ujjain',
        state: 'Madhya Pradesh',
        distanceKm: 38,
        cropId: 'soybean',
        cropName: 'Soybean (Yellow)',
        variety: 'JS 20-34 / FAQ',
        date: '20 Aug 2026',
        modalPrice: 4920,
        minPrice: 4500,
        maxPrice: 5180,
        previousPrice: 4770,
        priceChange: 150,
        priceChangePercent: 3.14,
        trend: 'increasing',
        arrivalVolumeTonnes: 480,
        isBestMandi: true,
        transportCostPerQtl: 80,
        netPayoutPerQtl: 4840,
        grade: 'Grade FAQ (Oil > 18%)',
      },
      {
        id: 'mandi_sb_indore',
        mandiName: 'Indore Laxmibai Nagar Mandi',
        district: 'Indore',
        state: 'Madhya Pradesh',
        distanceKm: 12,
        cropId: 'soybean',
        cropName: 'Soybean (Yellow)',
        variety: 'JS 95-60 / Super',
        date: '20 Aug 2026',
        modalPrice: 4850,
        minPrice: 4400,
        maxPrice: 5120,
        previousPrice: 4730,
        priceChange: 120,
        priceChangePercent: 2.54,
        trend: 'increasing',
        arrivalVolumeTonnes: 620,
        isBestMandi: false,
        transportCostPerQtl: 35,
        netPayoutPerQtl: 4815,
        grade: 'Grade A',
      },
      {
        id: 'mandi_sb_dewas',
        mandiName: 'Dewas Krishi Upaj Mandi',
        district: 'Dewas',
        state: 'Madhya Pradesh',
        distanceKm: 42,
        cropId: 'soybean',
        cropName: 'Soybean (Yellow)',
        variety: 'JS 20-29',
        date: '20 Aug 2026',
        modalPrice: 4780,
        minPrice: 4350,
        maxPrice: 4950,
        previousPrice: 4770,
        priceChange: 10,
        priceChangePercent: 0.21,
        trend: 'stable',
        arrivalVolumeTonnes: 210,
        isBestMandi: false,
        transportCostPerQtl: 85,
        netPayoutPerQtl: 4695,
        grade: 'FAQ Standard',
      },
      {
        id: 'mandi_sb_dhar',
        mandiName: 'Dhar Mandi Yard',
        district: 'Dhar',
        state: 'Madhya Pradesh',
        distanceKm: 65,
        cropId: 'soybean',
        cropName: 'Soybean (Yellow)',
        variety: 'JS 93-05',
        date: '20 Aug 2026',
        modalPrice: 4720,
        minPrice: 4300,
        maxPrice: 4900,
        previousPrice: 4780,
        priceChange: -60,
        priceChangePercent: -1.25,
        trend: 'decreasing',
        arrivalVolumeTonnes: 110,
        isBestMandi: false,
        transportCostPerQtl: 130,
        netPayoutPerQtl: 4590,
        grade: 'Standard',
      },
    ],
    history7d: [
      { date: '14 Aug', avgPrice: 4690, highestPrice: 4950, lowestPrice: 4250, arrivalTonnes: 980 },
      { date: '15 Aug', avgPrice: 4710, highestPrice: 4980, lowestPrice: 4280, arrivalTonnes: 850 },
      { date: '16 Aug', avgPrice: 4730, highestPrice: 5010, lowestPrice: 4300, arrivalTonnes: 1120 },
      { date: '17 Aug', avgPrice: 4760, highestPrice: 5050, lowestPrice: 4320, arrivalTonnes: 1250 },
      { date: '18 Aug', avgPrice: 4790, highestPrice: 5090, lowestPrice: 4350, arrivalTonnes: 1380 },
      { date: '19 Aug', avgPrice: 4820, highestPrice: 5140, lowestPrice: 4380, arrivalTonnes: 1400 },
      { date: '20 Aug', avgPrice: 4845, highestPrice: 5180, lowestPrice: 4400, arrivalTonnes: 1420 },
    ],
  },
  {
    cropId: 'wheat',
    cropName: 'Wheat (Gehun)',
    cropHindi: 'गेहूं (लोकवन / शरबती)',
    cropOdia: 'ଗହମ',
    icon: '🌾',
    category: 'Cereals',
    msp: 2275,
    currentDate: '20 Aug 2026',
    avgModalPrice: 2650,
    highestPrice: 3100,
    lowestPrice: 2350,
    bestMandiName: 'Sehore Krishi Mandi (Sharbati)',
    bestMandiPrice: 2710,
    bestMandiNetPayout: 2570,
    overallTrend: 'increasing',
    priceChangePercent: 2.8,
    totalArrivalTonnes: 2850,
    mandis: [
      {
        id: 'mandi_wh_sehore',
        mandiName: 'Sehore Krishi Mandi (Sharbati)',
        district: 'Sehore',
        state: 'Madhya Pradesh',
        distanceKm: 85,
        cropId: 'wheat',
        cropName: 'Wheat (Sharbati)',
        variety: 'Sharbati Premium',
        date: '20 Aug 2026',
        modalPrice: 2710,
        minPrice: 2450,
        maxPrice: 3100,
        previousPrice: 2620,
        priceChange: 90,
        priceChangePercent: 3.43,
        trend: 'increasing',
        arrivalVolumeTonnes: 720,
        isBestMandi: true,
        transportCostPerQtl: 140,
        netPayoutPerQtl: 2570,
        grade: 'Special Premium Gold',
      },
      {
        id: 'mandi_wh_ujjain',
        mandiName: 'Ujjain Mandi Yard',
        district: 'Ujjain',
        state: 'Madhya Pradesh',
        distanceKm: 38,
        cropId: 'wheat',
        cropName: 'Wheat (Lokwan)',
        variety: 'GW 322 / Lokwan',
        date: '20 Aug 2026',
        modalPrice: 2620,
        minPrice: 2400,
        maxPrice: 2900,
        previousPrice: 2560,
        priceChange: 60,
        priceChangePercent: 2.34,
        trend: 'increasing',
        arrivalVolumeTonnes: 980,
        isBestMandi: false,
        transportCostPerQtl: 80,
        netPayoutPerQtl: 2540,
        grade: 'Grade A Lokwan',
      },
      {
        id: 'mandi_wh_indore',
        mandiName: 'Indore APMC Chhavani',
        district: 'Indore',
        state: 'Madhya Pradesh',
        distanceKm: 14,
        cropId: 'wheat',
        cropName: 'Wheat (Milling)',
        variety: 'Mill Quality / Mixed',
        date: '20 Aug 2026',
        modalPrice: 2580,
        minPrice: 2350,
        maxPrice: 2850,
        previousPrice: 2540,
        priceChange: 40,
        priceChangePercent: 1.57,
        trend: 'increasing',
        arrivalVolumeTonnes: 1150,
        isBestMandi: false,
        transportCostPerQtl: 40,
        netPayoutPerQtl: 2540,
        grade: 'FAQ Standard',
      },
    ],
    history7d: [
      { date: '14 Aug', avgPrice: 2570, highestPrice: 2980, lowestPrice: 2300, arrivalTonnes: 2400 },
      { date: '15 Aug', avgPrice: 2585, highestPrice: 3000, lowestPrice: 2310, arrivalTonnes: 2200 },
      { date: '16 Aug', avgPrice: 2600, highestPrice: 3020, lowestPrice: 2320, arrivalTonnes: 2650 },
      { date: '17 Aug', avgPrice: 2615, highestPrice: 3040, lowestPrice: 2330, arrivalTonnes: 2700 },
      { date: '18 Aug', avgPrice: 2630, highestPrice: 3060, lowestPrice: 2340, arrivalTonnes: 2800 },
      { date: '19 Aug', avgPrice: 2640, highestPrice: 3080, lowestPrice: 2345, arrivalTonnes: 2820 },
      { date: '20 Aug', avgPrice: 2650, highestPrice: 3100, lowestPrice: 2350, arrivalTonnes: 2850 },
    ],
  },
  {
    cropId: 'paddy',
    cropName: 'Paddy / Rice (Dhan)',
    cropHindi: 'धान (चावल)',
    cropOdia: 'ଧାନ (ଚାଉଳ)',
    icon: '🌾',
    category: 'Cereals',
    msp: 2300,
    currentDate: '20 Aug 2026',
    avgModalPrice: 2340,
    highestPrice: 2510,
    lowestPrice: 2183,
    bestMandiName: 'Bargarh APMC Market',
    bestMandiPrice: 2380,
    bestMandiNetPayout: 2310,
    overallTrend: 'increasing',
    priceChangePercent: 1.9,
    totalArrivalTonnes: 3200,
    mandis: [
      {
        id: 'mandi_pd_bargarh',
        mandiName: 'Bargarh APMC Market',
        district: 'Bargarh',
        state: 'Odisha',
        distanceKm: 48,
        cropId: 'paddy',
        cropName: 'Paddy (Grade A)',
        variety: 'Pooja / Swarna',
        date: '20 Aug 2026',
        modalPrice: 2380,
        minPrice: 2200,
        maxPrice: 2510,
        previousPrice: 2335,
        priceChange: 45,
        priceChangePercent: 1.92,
        trend: 'increasing',
        arrivalVolumeTonnes: 1450,
        isBestMandi: true,
        transportCostPerQtl: 70,
        netPayoutPerQtl: 2310,
        grade: 'Grade A FAQ',
      },
      {
        id: 'mandi_pd_sambalpur',
        mandiName: 'Sambalpur RMC Yard',
        district: 'Sambalpur',
        state: 'Odisha',
        distanceKm: 18,
        cropId: 'paddy',
        cropName: 'Paddy (Common)',
        variety: 'MTU 1010',
        date: '20 Aug 2026',
        modalPrice: 2320,
        minPrice: 2183,
        maxPrice: 2450,
        previousPrice: 2305,
        priceChange: 15,
        priceChangePercent: 0.65,
        trend: 'stable',
        arrivalVolumeTonnes: 1100,
        isBestMandi: false,
        transportCostPerQtl: 40,
        netPayoutPerQtl: 2280,
        grade: 'Common Standard',
      },
      {
        id: 'mandi_pd_cuttack',
        mandiName: 'Cuttack Malgodown',
        district: 'Cuttack',
        state: 'Odisha',
        distanceKm: 120,
        cropId: 'paddy',
        cropName: 'Paddy (Common)',
        variety: 'Mixed Paddy',
        date: '20 Aug 2026',
        modalPrice: 2300,
        minPrice: 2183,
        maxPrice: 2420,
        previousPrice: 2300,
        priceChange: 0,
        priceChangePercent: 0,
        trend: 'stable',
        arrivalVolumeTonnes: 650,
        isBestMandi: false,
        transportCostPerQtl: 160,
        netPayoutPerQtl: 2140,
        grade: 'FAQ Standard',
      },
    ],
    history7d: [
      { date: '14 Aug', avgPrice: 2310, highestPrice: 2460, lowestPrice: 2183, arrivalTonnes: 2900 },
      { date: '15 Aug', avgPrice: 2315, highestPrice: 2470, lowestPrice: 2183, arrivalTonnes: 2750 },
      { date: '16 Aug', avgPrice: 2320, highestPrice: 2480, lowestPrice: 2183, arrivalTonnes: 3050 },
      { date: '17 Aug', avgPrice: 2325, highestPrice: 2490, lowestPrice: 2183, arrivalTonnes: 3100 },
      { date: '18 Aug', avgPrice: 2330, highestPrice: 2495, lowestPrice: 2183, arrivalTonnes: 3150 },
      { date: '19 Aug', avgPrice: 2335, highestPrice: 2500, lowestPrice: 2183, arrivalTonnes: 3180 },
      { date: '20 Aug', avgPrice: 2340, highestPrice: 2510, lowestPrice: 2183, arrivalTonnes: 3200 },
    ],
  },
  {
    cropId: 'cotton',
    cropName: 'Cotton (Kapas)',
    cropHindi: 'कपास (नरमा)',
    cropOdia: 'କପା',
    icon: '☁️',
    category: 'Cash Crops',
    msp: 7121,
    currentDate: '20 Aug 2026',
    avgModalPrice: 7480,
    highestPrice: 8050,
    lowestPrice: 6700,
    bestMandiName: 'Khandwa Mandi',
    bestMandiPrice: 7580,
    bestMandiNetPayout: 7460,
    overallTrend: 'increasing',
    priceChangePercent: 3.0,
    totalArrivalTonnes: 850,
    mandis: [
      {
        id: 'mandi_ct_khandwa',
        mandiName: 'Khandwa Cotton Yard',
        district: 'Khandwa',
        state: 'Madhya Pradesh',
        distanceKm: 62,
        cropId: 'cotton',
        cropName: 'Cotton (Long Staple)',
        variety: 'Bt Hybrid / Long Staple',
        date: '20 Aug 2026',
        modalPrice: 7580,
        minPrice: 6950,
        maxPrice: 8050,
        previousPrice: 7360,
        priceChange: 220,
        priceChangePercent: 2.98,
        trend: 'increasing',
        arrivalVolumeTonnes: 380,
        isBestMandi: true,
        transportCostPerQtl: 120,
        netPayoutPerQtl: 7460,
        grade: 'Long Staple 29mm+',
      },
      {
        id: 'mandi_ct_khargone',
        mandiName: 'Khargone APMC Mandi',
        district: 'Khargone',
        state: 'Madhya Pradesh',
        distanceKm: 78,
        cropId: 'cotton',
        cropName: 'Cotton (Medium Staple)',
        variety: 'Medium Staple FAQ',
        date: '20 Aug 2026',
        modalPrice: 7450,
        minPrice: 6800,
        maxPrice: 7900,
        previousPrice: 7270,
        priceChange: 180,
        priceChangePercent: 2.47,
        trend: 'increasing',
        arrivalVolumeTonnes: 340,
        isBestMandi: false,
        transportCostPerQtl: 140,
        netPayoutPerQtl: 7310,
        grade: 'Medium Staple 27mm',
      },
      {
        id: 'mandi_ct_burhanpur',
        mandiName: 'Burhanpur Mandi',
        district: 'Burhanpur',
        state: 'Madhya Pradesh',
        distanceKm: 110,
        cropId: 'cotton',
        cropName: 'Cotton (Uncleaned)',
        variety: 'Standard Rainfed',
        date: '20 Aug 2026',
        modalPrice: 7320,
        minPrice: 6700,
        maxPrice: 7750,
        previousPrice: 7410,
        priceChange: -90,
        priceChangePercent: -1.21,
        trend: 'decreasing',
        arrivalVolumeTonnes: 130,
        isBestMandi: false,
        transportCostPerQtl: 190,
        netPayoutPerQtl: 7130,
        grade: 'FAQ Standard',
      },
    ],
    history7d: [
      { date: '14 Aug', avgPrice: 7240, highestPrice: 7750, lowestPrice: 6600, arrivalTonnes: 720 },
      { date: '15 Aug', avgPrice: 7290, highestPrice: 7800, lowestPrice: 6650, arrivalTonnes: 690 },
      { date: '16 Aug', avgPrice: 7340, highestPrice: 7850, lowestPrice: 6680, arrivalTonnes: 780 },
      { date: '17 Aug', avgPrice: 7390, highestPrice: 7920, lowestPrice: 6700, arrivalTonnes: 810 },
      { date: '18 Aug', avgPrice: 7430, highestPrice: 7980, lowestPrice: 6700, arrivalTonnes: 830 },
      { date: '19 Aug', avgPrice: 7460, highestPrice: 8010, lowestPrice: 6700, arrivalTonnes: 840 },
      { date: '20 Aug', avgPrice: 7480, highestPrice: 8050, lowestPrice: 6700, arrivalTonnes: 850 },
    ],
  },
  {
    cropId: 'mustard',
    cropName: 'Mustard (Sarson)',
    cropHindi: 'सरसों (राई)',
    cropOdia: 'ସୋରିଷ',
    icon: '🌼',
    category: 'Oilseeds',
    msp: 5650,
    currentDate: '20 Aug 2026',
    avgModalPrice: 5680,
    highestPrice: 6050,
    lowestPrice: 5150,
    bestMandiName: 'Indore APMC Market',
    bestMandiPrice: 5720,
    bestMandiNetPayout: 5685,
    overallTrend: 'increasing',
    priceChangePercent: 2.5,
    totalArrivalTonnes: 920,
    mandis: [
      {
        id: 'mandi_ms_indore',
        mandiName: 'Indore APMC Market',
        district: 'Indore',
        state: 'Madhya Pradesh',
        distanceKm: 14,
        cropId: 'mustard',
        cropName: 'Mustard (Black/Yellow)',
        variety: 'Pusa Bold / FAQ',
        date: '20 Aug 2026',
        modalPrice: 5720,
        minPrice: 5300,
        maxPrice: 6050,
        previousPrice: 5580,
        priceChange: 140,
        priceChangePercent: 2.51,
        trend: 'increasing',
        arrivalVolumeTonnes: 420,
        isBestMandi: true,
        transportCostPerQtl: 35,
        netPayoutPerQtl: 5685,
        grade: 'High Oil Content (42%+)',
      },
      {
        id: 'mandi_ms_morena',
        mandiName: 'Morena Krishi Upaj Mandi',
        district: 'Morena',
        state: 'Madhya Pradesh',
        distanceKm: 140,
        cropId: 'mustard',
        cropName: 'Mustard (Bold)',
        variety: 'NRCHB 101',
        date: '20 Aug 2026',
        modalPrice: 5650,
        minPrice: 5200,
        maxPrice: 5980,
        previousPrice: 5540,
        priceChange: 110,
        priceChangePercent: 1.98,
        trend: 'increasing',
        arrivalVolumeTonnes: 320,
        isBestMandi: false,
        transportCostPerQtl: 210,
        netPayoutPerQtl: 5440,
        grade: 'Grade A FAQ',
      },
      {
        id: 'mandi_ms_ujjain',
        mandiName: 'Ujjain Mandi Yard',
        district: 'Ujjain',
        state: 'Madhya Pradesh',
        distanceKm: 38,
        cropId: 'mustard',
        cropName: 'Mustard (Standard)',
        variety: 'Standard Yellow',
        date: '20 Aug 2026',
        modalPrice: 5580,
        minPrice: 5150,
        maxPrice: 5890,
        previousPrice: 5580,
        priceChange: 0,
        priceChangePercent: 0,
        trend: 'stable',
        arrivalVolumeTonnes: 180,
        isBestMandi: false,
        transportCostPerQtl: 80,
        netPayoutPerQtl: 5500,
        grade: 'Standard',
      },
    ],
    history7d: [
      { date: '14 Aug', avgPrice: 5520, highestPrice: 5850, lowestPrice: 5050, arrivalTonnes: 810 },
      { date: '15 Aug', avgPrice: 5550, highestPrice: 5890, lowestPrice: 5080, arrivalTonnes: 780 },
      { date: '16 Aug', avgPrice: 5580, highestPrice: 5920, lowestPrice: 5100, arrivalTonnes: 850 },
      { date: '17 Aug', avgPrice: 5610, highestPrice: 5960, lowestPrice: 5120, arrivalTonnes: 880 },
      { date: '18 Aug', avgPrice: 5640, highestPrice: 6000, lowestPrice: 5130, arrivalTonnes: 900 },
      { date: '19 Aug', avgPrice: 5660, highestPrice: 6020, lowestPrice: 5140, arrivalTonnes: 910 },
      { date: '20 Aug', avgPrice: 5680, highestPrice: 6050, lowestPrice: 5150, arrivalTonnes: 920 },
    ],
  },
  {
    cropId: 'chickpea',
    cropName: 'Gram / Chana (Chickpea)',
    cropHindi: 'चना (देसी / काबुली)',
    cropOdia: 'ବୁଟ',
    icon: '🟤',
    category: 'Pulses',
    msp: 5440,
    currentDate: '20 Aug 2026',
    avgModalPrice: 6090,
    highestPrice: 6600,
    lowestPrice: 5500,
    bestMandiName: 'Indore APMC Mandi',
    bestMandiPrice: 6150,
    bestMandiNetPayout: 6115,
    overallTrend: 'increasing',
    priceChangePercent: 2.2,
    totalArrivalTonnes: 1150,
    mandis: [
      {
        id: 'mandi_ch_indore',
        mandiName: 'Indore APMC Mandi',
        district: 'Indore',
        state: 'Madhya Pradesh',
        distanceKm: 14,
        cropId: 'chickpea',
        cropName: 'Chana (Desi Bold)',
        variety: 'JG 11 / Dollar Bold',
        date: '20 Aug 2026',
        modalPrice: 6150,
        minPrice: 5600,
        maxPrice: 6600,
        previousPrice: 6020,
        priceChange: 130,
        priceChangePercent: 2.16,
        trend: 'increasing',
        arrivalVolumeTonnes: 580,
        isBestMandi: true,
        transportCostPerQtl: 35,
        netPayoutPerQtl: 6115,
        grade: 'Grade A Desi Bold',
      },
      {
        id: 'mandi_ch_vidisha',
        mandiName: 'Vidisha Krishi Upaj Mandi',
        district: 'Vidisha',
        state: 'Madhya Pradesh',
        distanceKm: 115,
        cropId: 'chickpea',
        cropName: 'Chana (Desi)',
        variety: 'JAKI 9218',
        date: '20 Aug 2026',
        modalPrice: 6100,
        minPrice: 5550,
        maxPrice: 6520,
        previousPrice: 6020,
        priceChange: 80,
        priceChangePercent: 1.33,
        trend: 'increasing',
        arrivalVolumeTonnes: 340,
        isBestMandi: false,
        transportCostPerQtl: 180,
        netPayoutPerQtl: 5920,
        grade: 'FAQ Standard',
      },
      {
        id: 'mandi_ch_dewas',
        mandiName: 'Dewas Mandi Yard',
        district: 'Dewas',
        state: 'Madhya Pradesh',
        distanceKm: 42,
        cropId: 'chickpea',
        cropName: 'Chana (Standard)',
        variety: 'Mixed Chana',
        date: '20 Aug 2026',
        modalPrice: 6020,
        minPrice: 5500,
        maxPrice: 6450,
        previousPrice: 6020,
        priceChange: 0,
        priceChangePercent: 0,
        trend: 'stable',
        arrivalVolumeTonnes: 230,
        isBestMandi: false,
        transportCostPerQtl: 85,
        netPayoutPerQtl: 5935,
        grade: 'Standard',
      },
    ],
    history7d: [
      { date: '14 Aug', avgPrice: 5920, highestPrice: 6380, lowestPrice: 5400, arrivalTonnes: 950 },
      { date: '15 Aug', avgPrice: 5960, highestPrice: 6420, lowestPrice: 5420, arrivalTonnes: 920 },
      { date: '16 Aug', avgPrice: 6000, highestPrice: 6480, lowestPrice: 5450, arrivalTonnes: 1040 },
      { date: '17 Aug', avgPrice: 6030, highestPrice: 6520, lowestPrice: 5480, arrivalTonnes: 1090 },
      { date: '18 Aug', avgPrice: 6060, highestPrice: 6560, lowestPrice: 5490, arrivalTonnes: 1120 },
      { date: '19 Aug', avgPrice: 6080, highestPrice: 6580, lowestPrice: 5500, arrivalTonnes: 1140 },
      { date: '20 Aug', avgPrice: 6090, highestPrice: 6600, lowestPrice: 5500, arrivalTonnes: 1150 },
    ],
  },
  {
    cropId: 'maize',
    cropName: 'Maize (Makka / Corn)',
    cropHindi: 'मक्का (मकई)',
    cropOdia: 'ମକା',
    icon: '🌽',
    category: 'Cereals',
    msp: 2090,
    currentDate: '20 Aug 2026',
    avgModalPrice: 2190,
    highestPrice: 2420,
    lowestPrice: 1880,
    bestMandiName: 'Chhindwara Mandi',
    bestMandiPrice: 2240,
    bestMandiNetPayout: 2080,
    overallTrend: 'increasing',
    priceChangePercent: 2.7,
    totalArrivalTonnes: 1650,
    mandis: [
      {
        id: 'mandi_mz_chhindwara',
        mandiName: 'Chhindwara Mandi (Corn City)',
        district: 'Chhindwara',
        state: 'Madhya Pradesh',
        distanceKm: 160,
        cropId: 'maize',
        cropName: 'Maize (Yellow Feed)',
        variety: 'Pioneer Hybrid / Yellow',
        date: '20 Aug 2026',
        modalPrice: 2240,
        minPrice: 1950,
        maxPrice: 2420,
        previousPrice: 2180,
        priceChange: 60,
        priceChangePercent: 2.75,
        trend: 'increasing',
        arrivalVolumeTonnes: 850,
        isBestMandi: true,
        transportCostPerQtl: 240,
        netPayoutPerQtl: 2000,
        grade: 'Grade A Yellow (Moisture < 12%)',
      },
      {
        id: 'mandi_mz_indore',
        mandiName: 'Indore Mandi Yard',
        district: 'Indore',
        state: 'Madhya Pradesh',
        distanceKm: 14,
        cropId: 'maize',
        cropName: 'Maize (Industrial)',
        variety: 'DKC 9108',
        date: '20 Aug 2026',
        modalPrice: 2180,
        minPrice: 1900,
        maxPrice: 2350,
        previousPrice: 2180,
        priceChange: 0,
        priceChangePercent: 0,
        trend: 'stable',
        arrivalVolumeTonnes: 520,
        isBestMandi: false,
        transportCostPerQtl: 35,
        netPayoutPerQtl: 2145,
        grade: 'FAQ Standard',
      },
      {
        id: 'mandi_mz_sambalpur',
        mandiName: 'Sambalpur APMC',
        district: 'Sambalpur',
        state: 'Odisha',
        distanceKm: 18,
        cropId: 'maize',
        cropName: 'Maize (Feed Quality)',
        variety: 'Local Hybrid',
        date: '20 Aug 2026',
        modalPrice: 2150,
        minPrice: 1880,
        maxPrice: 2300,
        previousPrice: 2190,
        priceChange: -40,
        priceChangePercent: -1.82,
        trend: 'decreasing',
        arrivalVolumeTonnes: 280,
        isBestMandi: false,
        transportCostPerQtl: 40,
        netPayoutPerQtl: 2110,
        grade: 'Standard',
      },
    ],
    history7d: [
      { date: '14 Aug', avgPrice: 2120, highestPrice: 2320, lowestPrice: 1850, arrivalTonnes: 1400 },
      { date: '15 Aug', avgPrice: 2140, highestPrice: 2340, lowestPrice: 1860, arrivalTonnes: 1350 },
      { date: '16 Aug', avgPrice: 2150, highestPrice: 2360, lowestPrice: 1860, arrivalTonnes: 1520 },
      { date: '17 Aug', avgPrice: 2165, highestPrice: 2380, lowestPrice: 1870, arrivalTonnes: 1580 },
      { date: '18 Aug', avgPrice: 2175, highestPrice: 2400, lowestPrice: 1875, arrivalTonnes: 1610 },
      { date: '19 Aug', avgPrice: 2185, highestPrice: 2410, lowestPrice: 1880, arrivalTonnes: 1630 },
      { date: '20 Aug', avgPrice: 2190, highestPrice: 2420, lowestPrice: 1880, arrivalTonnes: 1650 },
    ],
  },
  {
    cropId: 'tomato',
    cropName: 'Tomato (Tamatar)',
    cropHindi: 'टमाटर',
    cropOdia: 'ବିଲାତି ବାଇଗଣ',
    icon: '🍅',
    category: 'Vegetables',
    msp: 0,
    currentDate: '20 Aug 2026',
    avgModalPrice: 1840,
    highestPrice: 2500,
    lowestPrice: 1100,
    bestMandiName: 'Ujjain Vegetable Mandi',
    bestMandiPrice: 1920,
    bestMandiNetPayout: 1840,
    overallTrend: 'decreasing',
    priceChangePercent: -9.8,
    totalArrivalTonnes: 2100,
    mandis: [
      {
        id: 'mandi_tm_ujjain',
        mandiName: 'Ujjain Vegetable Mandi',
        district: 'Ujjain',
        state: 'Madhya Pradesh',
        distanceKm: 38,
        cropId: 'tomato',
        cropName: 'Tomato (Hybrid Red)',
        variety: 'Abhinav / US 440',
        date: '20 Aug 2026',
        modalPrice: 1920,
        minPrice: 1300,
        maxPrice: 2500,
        previousPrice: 2100,
        priceChange: -180,
        priceChangePercent: -8.57,
        trend: 'decreasing',
        arrivalVolumeTonnes: 780,
        isBestMandi: true,
        transportCostPerQtl: 80,
        netPayoutPerQtl: 1840,
        grade: 'Firm Red Grade A',
      },
      {
        id: 'mandi_tm_indore',
        mandiName: 'Indore Choithram Mandi',
        district: 'Indore',
        state: 'Madhya Pradesh',
        distanceKm: 8,
        cropId: 'tomato',
        cropName: 'Tomato (Local Red)',
        variety: 'Hybrid Salad Tomato',
        date: '20 Aug 2026',
        modalPrice: 1850,
        minPrice: 1200,
        maxPrice: 2400,
        previousPrice: 2100,
        priceChange: -250,
        priceChangePercent: -11.9,
        trend: 'decreasing',
        arrivalVolumeTonnes: 1100,
        isBestMandi: false,
        transportCostPerQtl: 25,
        netPayoutPerQtl: 1825,
        grade: 'Standard Ripe',
      },
      {
        id: 'mandi_tm_bhopal',
        mandiName: 'Bhopal Karond Sabzi Mandi',
        district: 'Bhopal',
        state: 'Madhya Pradesh',
        distanceKm: 180,
        cropId: 'tomato',
        cropName: 'Tomato (Standard)',
        variety: 'Local Desi',
        date: '20 Aug 2026',
        modalPrice: 1750,
        minPrice: 1100,
        maxPrice: 2250,
        previousPrice: 2050,
        priceChange: -300,
        priceChangePercent: -14.6,
        trend: 'decreasing',
        arrivalVolumeTonnes: 220,
        isBestMandi: false,
        transportCostPerQtl: 260,
        netPayoutPerQtl: 1490,
        grade: 'Mixed Bulk',
      },
    ],
    history7d: [
      { date: '14 Aug', avgPrice: 2450, highestPrice: 3100, lowestPrice: 1700, arrivalTonnes: 1300 },
      { date: '15 Aug', avgPrice: 2380, highestPrice: 3000, lowestPrice: 1650, arrivalTonnes: 1420 },
      { date: '16 Aug', avgPrice: 2250, highestPrice: 2900, lowestPrice: 1500, arrivalTonnes: 1680 },
      { date: '17 Aug', avgPrice: 2120, highestPrice: 2750, lowestPrice: 1400, arrivalTonnes: 1850 },
      { date: '18 Aug', avgPrice: 2010, highestPrice: 2650, lowestPrice: 1300, arrivalTonnes: 1950 },
      { date: '19 Aug', avgPrice: 1920, highestPrice: 2580, lowestPrice: 1200, arrivalTonnes: 2020 },
      { date: '20 Aug', avgPrice: 1840, highestPrice: 2500, lowestPrice: 1100, arrivalTonnes: 2100 },
    ],
  },
  {
    cropId: 'onion',
    cropName: 'Onion (Pyaaz)',
    cropHindi: 'प्याज (लाल)',
    cropOdia: 'ପିଆଜ',
    icon: '🧅',
    category: 'Vegetables',
    msp: 0,
    currentDate: '20 Aug 2026',
    avgModalPrice: 2380,
    highestPrice: 2900,
    lowestPrice: 1700,
    bestMandiName: 'Indore APMC Mandi',
    bestMandiPrice: 2450,
    bestMandiNetPayout: 2415,
    overallTrend: 'increasing',
    priceChangePercent: 6.5,
    totalArrivalTonnes: 3400,
    mandis: [
      {
        id: 'mandi_on_indore',
        mandiName: 'Indore APMC Mandi',
        district: 'Indore',
        state: 'Madhya Pradesh',
        distanceKm: 14,
        cropId: 'onion',
        cropName: 'Onion (Red Medium-Bold)',
        variety: 'Nashik Red / Malwa Red',
        date: '20 Aug 2026',
        modalPrice: 2450,
        minPrice: 1800,
        maxPrice: 2900,
        previousPrice: 2300,
        priceChange: 150,
        priceChangePercent: 6.52,
        trend: 'increasing',
        arrivalVolumeTonnes: 1800,
        isBestMandi: true,
        transportCostPerQtl: 35,
        netPayoutPerQtl: 2415,
        grade: 'Super Red Bold (45mm+)',
      },
      {
        id: 'mandi_on_neemuch',
        mandiName: 'Neemuch Krishi Mandi',
        district: 'Neemuch',
        state: 'Madhya Pradesh',
        distanceKm: 230,
        cropId: 'onion',
        cropName: 'Onion (Storage Quality)',
        variety: 'Garlic & Onion Special',
        date: '20 Aug 2026',
        modalPrice: 2380,
        minPrice: 1750,
        maxPrice: 2820,
        previousPrice: 2280,
        priceChange: 100,
        priceChangePercent: 4.39,
        trend: 'increasing',
        arrivalVolumeTonnes: 950,
        isBestMandi: false,
        transportCostPerQtl: 320,
        netPayoutPerQtl: 2060,
        grade: 'Grade A Dry Cured',
      },
      {
        id: 'mandi_on_mandsaur',
        mandiName: 'Mandsaur Mandi Yard',
        district: 'Mandsaur',
        state: 'Madhya Pradesh',
        distanceKm: 190,
        cropId: 'onion',
        cropName: 'Onion (Medium)',
        variety: 'Medium Mix',
        date: '20 Aug 2026',
        modalPrice: 2320,
        minPrice: 1700,
        maxPrice: 2750,
        previousPrice: 2320,
        priceChange: 0,
        priceChangePercent: 0,
        trend: 'stable',
        arrivalVolumeTonnes: 650,
        isBestMandi: false,
        transportCostPerQtl: 280,
        netPayoutPerQtl: 2040,
        grade: 'Standard',
      },
    ],
    history7d: [
      { date: '14 Aug', avgPrice: 2180, highestPrice: 2650, lowestPrice: 1550, arrivalTonnes: 2800 },
      { date: '15 Aug', avgPrice: 2220, highestPrice: 2700, lowestPrice: 1580, arrivalTonnes: 2900 },
      { date: '16 Aug', avgPrice: 2260, highestPrice: 2750, lowestPrice: 1600, arrivalTonnes: 3100 },
      { date: '17 Aug', avgPrice: 2300, highestPrice: 2800, lowestPrice: 1640, arrivalTonnes: 3250 },
      { date: '18 Aug', avgPrice: 2330, highestPrice: 2840, lowestPrice: 1660, arrivalTonnes: 3300 },
      { date: '19 Aug', avgPrice: 2360, highestPrice: 2880, lowestPrice: 1680, arrivalTonnes: 3350 },
      { date: '20 Aug', avgPrice: 2380, highestPrice: 2900, lowestPrice: 1700, arrivalTonnes: 3400 },
    ],
  },
];

export const marketService = {
  /**
   * Get all crop market summaries
   */
  async getAllCropMarketData(): Promise<CropMarketData[]> {
    // Simulated async fetch with DEMO DATA
    await new Promise(resolve => setTimeout(resolve, 200));
    return DEMO_CROP_MARKET_DATA;
  },

  /**
   * Get market data for a specific crop
   */
  async getCropMarketData(cropId: string): Promise<CropMarketData> {
    await new Promise(resolve => setTimeout(resolve, 150));
    const match = DEMO_CROP_MARKET_DATA.find(c => c.cropId.toLowerCase() === cropId.toLowerCase());
    return match || DEMO_CROP_MARKET_DATA[0];
  },

  /**
   * Get all individual mandi records across all crops or filtered
   */
  async getMandiRecords(params?: { cropId?: string; state?: string; district?: string }): Promise<MandiRecord[]> {
    await new Promise(resolve => setTimeout(resolve, 150));
    let records: MandiRecord[] = [];
    DEMO_CROP_MARKET_DATA.forEach(cropData => {
      if (!params?.cropId || cropData.cropId.toLowerCase() === params.cropId.toLowerCase()) {
        records.push(...cropData.mandis);
      }
    });

    if (params?.state && params.state !== 'All') {
      records = records.filter(r => r.state.toLowerCase().includes(params.state!.toLowerCase()));
    }

    if (params?.district && params.district !== 'All') {
      records = records.filter(r => r.district.toLowerCase().includes(params.district!.toLowerCase()));
    }

    return records;
  },

  /**
   * Calculate harvest lot profit across mandis
   */
  calculateLotComparison(cropData: CropMarketData, quantityQuintals: number) {
    return cropData.mandis.map(mandi => {
      const grossRevenue = mandi.modalPrice * quantityQuintals;
      const totalTransport = mandi.transportCostPerQtl * quantityQuintals;
      const netProfit = grossRevenue - totalTransport;
      return {
        mandiId: mandi.id,
        mandiName: mandi.mandiName,
        distanceKm: mandi.distanceKm,
        pricePerQtl: mandi.modalPrice,
        transportCostPerQtl: mandi.transportCostPerQtl,
        netPayoutPerQtl: mandi.netPayoutPerQtl,
        grossRevenue,
        totalTransport,
        netProfit,
        isBestMandi: mandi.isBestMandi,
      };
    }).sort((a, b) => b.netProfit - a.netProfit);
  },

  /**
   * Legacy interface compatibility
   */
  async getMandiPrices(state?: string, crop?: string): Promise<MarketPrice[]> {
    const records = await this.getMandiRecords({ state, cropId: crop });
    return records.map(r => ({
      id: r.id,
      crop: r.cropName,
      mandi: r.mandiName,
      state: r.state,
      currentPrice: r.modalPrice,
      modalPrice: r.modalPrice,
      priceChangePercent: r.priceChangePercent,
      trend: r.trend === 'increasing' ? 'up' : (r.trend === 'decreasing' ? 'down' : 'stable'),
      unit: '₹ / Quintal',
    }));
  },

  async getPriceTrends(cropId: string, days: number = 7): Promise<{ date: string; price: number }[]> {
    const data = await this.getCropMarketData(cropId);
    return data.history7d.slice(-days).map(h => ({
      date: h.date,
      price: h.avgPrice,
    }));
  }
};
